kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "helm.fullname" .}}-secret"
stringData:
  EXAMPLE_ENV_VAR: "put your secrets env vars here"
  ANOTHER_EXAMPLE: "{{ .Values.app.examplePassword }}"